### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by roman01la** [zelark/clj-chat#1]
- I don't think this is needed if you have it in `preloads` in build config [code](https://github.com/zelark/clj-chat/blob/2c11990e4fc8e4597d9e4d0acdc4a16416d015b7/src/clj_chat/core.cljs#L8)
- Use `goog.object/get` so unkown properties won't be renamed when compiling in advanced mode [code](https://github.com/zelark/clj-chat/blob/master/src/clj_chat/db.cljs#L26-L29)
- Private vars, usually it's better to keep var public and denote it as private with leading dash, `defn -image-url` instead of `defn- image-url` [code](https://github.com/zelark/clj-chat/blob/master/src/clj_chat/fb-api.cljs#L13)
- This could be `#js {}` instead of converting from clj `clj->js` [code](https://github.com/zelark/clj-chat/blob/master/src/clj_chat/core.cljs#L14)
- Boolean returning functions could be hinted with return type such that compiler will emit fast check when function is used in conditional expression [code](https://github.com/zelark/clj-chat/blob/master/src/clj_chat/views.cljs#L12)

without type hint
```clj
(defn me?  [username])
(when (me? nil) 1)
```
```js
cljs.user.me_QMARK_ = (function cljs$user$me_QMARK_(username){
  return null;
});
if(cljs.core.truth_(cljs.user.me_QMARK_.call(null,null))){
} else {
}
```

with type hint
```clj
(defn ^boolean me? [username])
(when (me? nil) 1)
```
```js
cljs.user.me_QMARK_ = (function cljs$user$me_QMARK_(username){
  return null;
});
if(cljs.user.me_QMARK_.call(null,null)){
} else {
}
```

- Create js obj instead [code](https://github.com/zelark/clj-chat/blob/master/src/clj_chat/views.cljs#L22)
- Header could be a separate components bc it is reused on multiple screens [code](https://github.com/zelark/clj-chat/blob/master/src/clj_chat/views.cljs#L63)

**Comment by zelark** [comment]
Thanks for review and feedback. It was very helpful to me, so far as I am a newbie in ClojureScript.

But one thing haunts my mind:
> Private vars, usually it's better to keep var public and denote it as private with leading dash

I wonder where this rule comes: is it some convention or what? And why is it better? I googled but found nothing relevant to. Explain please.

**Comment by roman01la** [comment]
Ok, this is not convention or something. It's more based on personal experience, when something is forbidden it's harder to change this eventually when it will be needed, rather than keeping yourself disciplined and not using "private" var. But that's just personal taste, you can ignore it.

**Comment by zelark** [comment]
Thank you. I got it.
Maybe I change my preference after a while, but for now, I'll prefer to stay with private functions. Might because of my Java background.
